export const products = [
  {
    id: 1,
    name: "Product 1",
    image: "../src/assets/first.jpg",
    price: 29.99,
    rating: 2,
  },
  {
    id: 2,
    name: "Product 2",
    image: "../src/assets/download (2).jpg",
    price: 19.99,
    rating: 1,
  },
  {
    id: 3,
    name: "Product 3",
    image: "../src/assets/download (3).jpg",
    price: 39.99,
    rating: 5,
  },
  {
    id: 4,
    name: "Product 1",
    image: "../src/assets/download.jpg",
    price: 29.99,
    rating: 2,
  },
  {
    id: 5,
    name: "Product 2",
    image: "../src/assets/download.jpg",
    price: 19.99,
    rating: 3,
  },
  {
    id: 6,
    name: "Product 3",
    image: "../src/assets/first.jpg",
    price: 39.99,
    rating: 4,
  },
  {
    id: 7,
    name: "Product 1",
    image: "../src/assets/download (2).jpg",
    price: 29.99,
    rating: 5,
  },
  {
    id: 8,
    name: "Product 2",
    image: "../src/assets/download (3).jpg",
    price: 19.99,
    rating: 2,
  },
  {
    id: 9,
    name: "Product 3",
    image: "../src/assets/download.jpg",
    price: 39.99,
    rating: 3,
  },
];
